# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fullname.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fullname.proto',
  package='fullnameProto',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x66ullname.proto\x12\rfullnameProto\"/\n\x08\x46ullname\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FULLNAME = _descriptor.Descriptor(
  name='Fullname',
  full_name='fullnameProto.Fullname',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstname', full_name='fullnameProto.Fullname.firstname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastname', full_name='fullnameProto.Fullname.lastname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['Fullname'] = _FULLNAME

Fullname = _reflection.GeneratedProtocolMessageType('Fullname', (_message.Message,), dict(
  DESCRIPTOR = _FULLNAME,
  __module__ = 'fullname_pb2'
  # @@protoc_insertion_point(class_scope:fullnameProto.Fullname)
  ))
_sym_db.RegisterMessage(Fullname)


# @@protoc_insertion_point(module_scope)
